name: 14 - secrets scan on our repository

on:
    pull_request:
    push:
    workflow_dispatch:
    workflow_call:
    schedule:
        - cron: "00 12 * * *"

jobs:
    scan:
        name: gitleaks
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v7
              with:
                fetch-depth: 0
            - uses: gitleaks/gitleaks-action@v3
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Only required for Organizations, not personal accounts.