name: 18 - call other workflows

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    secrets-scan:
        uses: ./.github/workflows/14-secrets-scan.yaml

    dependency-scan:
        uses: ./.github/workflows/15-dependency-scan.yaml

    codequality-scan:
        uses: ./.github/workflows/17-codequality.yaml